### ISSUE TITLE
The installation instruction produces an error

### ISSUE THREAD

**Issue by pakom** [i-akiya/R4DSXML#1]
The installation instruction `install_github("i-akiya/R4DSXML/R4DSXML", ref ="v0.4.1RC1")` produces an error: `Error in stop(github_error(request)) : Not Found (404)`. No installation is performed.

I am using R 3.3.1 in Arch Linux.

**Comment by i-akiya** [comment]
I did't update install instruction.
Corrected install command is following.

library(devtools)
install_github("DataDrivenInc/R4DSXML/R4DSXML")

Now, README.md is updated.

**Comment by pakom** [comment]
Thank you very much for the **SWIFT** reaction!
